baseurl = "https://loveorange.github.io"
languageCode = "en-us"
title = "Lin's Poem"
theme = "noteworthy"
# theme = "pure"
preserveTaxonomyNames = true
disqusShortname = "lin-poem"
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 3 # Configure how long the post summary should be on the homepage.


[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "home"
  weight = 1

# [[menu.main]]
#   name = "Blog"
#   url = "/posts/"
#   identifier = "main"
#   weight = 2

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  identifier = "categories"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  identifier = "tags"
  weight = 4

# [[menu.main]]
#   name = "About"
#   url = "/about/"
#   identifier = "about"
#   weight = 4


[params]
  github           = "LoveOrange"
  # gitlab           = ""
  # stackoverflow    = "" # User Number
  # medium           = ""
  linkedin         = "%E6%9E%97-%E5%A7%9C-6b3949a1/"
  # facebook         = "example"
  # quora            = ""
  # youtube          = ""
  wechat         = "lovezc622"
  qq             = "470729897" # User ID Number
  # instagram        = "example"
  # twitter          = "example"
  email            = "orange24k@hotmail.com"
